### ISSUE TITLE
"label_files" in the apple CT dataset

### ISSUE THREAD

**Issue by liutianlin0121** [jleuschn/learned_ct_reco_comparison_paper#1]
Hi Johannes,

Thanks a lot for this comprehensive study!

In the `util/apples_data.py` I am wondering where can I find the `label_files` defined in the line

`label_files = os.listdir(os.path.join(config['data_path'], 'labels'))`

It seems that I couldn't find this file in the apple CT dataset webpage https://zenodo.org/record/4212301#.YKqogIaxXds Perhaps I miss something? 

Another questions is that, I see that the `util/apples_data.py` script loads data from  `projections_noisefree`, `projections_gaussian_noise`, and `projections_scattering` folders. I suppose they correspond to folders  `Dataset_A`, `Dataset_B`, and `Dataset_C`, respectively in the apple CT dataset webpage?

Thanks a lot!

Cheers,
Tianlin

**Comment by jleuschn** [comment]
Hi Tianlin,

thanks for your participation in the Sprint, and sorry for the late reply.

The code is based on the original data structure that was used for the Apple-CT challenge (which can still be accessed after [registering for the Code Sprint 2020](http://dival.math.uni-bremen.de/code_sprint_2020/register/) and joining the [Apple-CT Challenge](https://apples-ct.grand-challenge.org/)). In the meantime the data has been slightly reorganized and uploaded to zenodo (as you mentioned), and is documented by [1]. For future experiments, this public dataset should be used.

Exactly, the datasets A, B and C correspond to noise-free, Gaussian and scattering, respectively.

Best regards,
Johannes

[1]: S.B. Coban, V. Andriiashen, P.S. Ganguly, M. v. Eijnatten, K.J. Batenburg, 2020, Parallel-beam X-ray CT datasets of apples with internal defects and label balancing for machine learning, [arXiv:2012.13346](https://arxiv.org/abs/2012.13346)

**Comment by liutianlin0121** [comment]
Thanks a lot! I'll check out the sprint version of the data.

**Comment by songjiechong** [comment]
> Hi Johannes,
> 
> Thanks a lot for this comprehensive study!
> 
> In the `util/apples_data.py` I am wondering where can I find the `label_files` defined in the line
> 
> `label_files = os.listdir(os.path.join(config['data_path'], 'labels'))`
> 
> It seems that I couldn't find this file in the apple CT dataset webpage https://zenodo.org/record/4212301#.YKqogIaxXds Perhaps I miss something?
> 
> Another questions is that, I see that the `util/apples_data.py` script loads data from `projections_noisefree`, `projections_gaussian_noise`, and `projections_scattering` folders. I suppose they correspond to folders `Dataset_A`, `Dataset_B`, and `Dataset_C`, respectively in the apple CT dataset webpage?
> 
> Thanks a lot!
> 
> Cheers,
> Tianlin

Hello! I want to know whether you find the "labels" file.

**Comment by jleuschn** [comment]
Hi,

the data is available from the [Apples-CT Challenge](https://apples-ct.grand-challenge.org/) once you joined the challenge.

Best regards,
Johannes
